### ISSUE TITLE
join game bug

### ISSUE THREAD

**Issue by SuphakornHomnan** [mrkwskiti/WerewolfClient#5]
can't join game when login by sign up.

**Comment by SuphakornHomnan** [comment]
I think _game.Id is null it threw expection.
(Probably => NullReferenceException)

**Comment by kitimark** [comment]
did you try to fix it?

**Comment by SuphakornHomnan** [comment]
Not yet.

**Comment by SuphakornHomnan** [comment]
I can deal it. 
yeah!!
